# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/',
                'doc_host': 'https://la3d.github.io',
                'git_url': 'https://github.com/la3d/cellrag',
                'lib_path': 'cellRAG'},
  'syms': {'cellRAG.core': {'cellRAG.core.foo': ('core.html#foo', 'cellRAG/core.py')}}}
